### ISSUE TITLE
博主 运行失败是因为怎么啊

### ISSUE THREAD

**Issue by 2714570426** [rxrw/daily_morning#14]
错误原因是：Process completed with exit code 1.

**Comment by fromann** [comment]
大佬这个时间格式我设置的**2003-02-03**
但是还是显示错误
···
Traceback (most recent call last):
  File "/home/runner/work/dailyMessage/dailyMessage/./main.py", line [51](https://github.com/fromann/dailyMessage/runs/7943189932?check_suite_focus=true#step:4:52), in <module>
    data = {"weather":{"value":wea},"temperature":{"value":temperature},"born_days":{"value":get_count()},"birthday_left":{"value":get_birthday()},"words":{"value":get_words(), "color":get_random_color()}}
  File "/home/runner/work/dailyMessage/dailyMessage/./main.py", line 28, in get_count
    delta = today - datetime.strptime(start_date, "%Y-%m-%d")
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/_strptime.py", line [56](https://github.com/fromann/dailyMessage/runs/7943189932?check_suite_focus=true#step:4:57)8, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y-%m-%d'
Error: Process completed with exit code 1.
···

**Comment by beichen123-hub** [comment]
微信公众平台 模板内容里面的参数写错了 {{xxxxx.DATA}}这样的形式，纪念日要这样写{{love days.DATA}} 有一个下划线，参数不能空格。

**Comment by BypassKing** [comment]
我运行错误

`Traceback (most recent call last):
  File "/home/runner/work/npy/npy/./main.py", line [52](https://github.com/BypassKing/npy/runs/7947721027?check_suite_focus=true#step:4:53), in <module>
    res = wm.send_template(user_id, template_id, data)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/wechatpy/client/api/message.py", line 609, in send_template
    return self._post(
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/wechatpy/client/api/base.py", line 19, in _post
    return self._client.post(url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/wechatpy/client/base.py", line 182, in post
    return self._request(
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/wechatpy/client/base.py", line 101, in _request
    return self._handle_result(
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/wechatpy/client/base.py", line 1[58](https://github.com/BypassKing/npy/runs/7947721027?check_suite_focus=true#step:4:59), in _handle_result
    raise WeChatClientException(
wechatpy.exceptions.WeChatClientException: Error code: 40003, message: invalid openid rid: 630340[59](https://github.com/BypassKing/npy/runs/7947721027?check_suite_focus=true#step:4:60)-6ecf07ac-3305bab6
Error: Process completed with exit code 1.`

**Comment by BypassKing** [comment]
wx模版内容
`天气:{{weather.DATA}} 
温度:{{temperature.DATA}} 
今天是你们的第{{love_days.DATA}}天 
距离她的生日还有{{birthday_left.DATA}}天 
{{words.DATA}}`
模版标题为
xxxx小可爱♡♡♡

是这个桃心的符号吗？
我试试
