### ISSUE TITLE
按照格式输入的start_days 还是显示错误

### ISSUE THREAD

**Issue by fromann** [rxrw/daily_morning#15]
大佬这个时间格式我设置的**2003-02-03**
但是还是显示错误
~~~
Traceback (most recent call last):
  File "/home/runner/work/dailyMessage/dailyMessage/./main.py", line [51](https://github.com/fromann/dailyMessage/runs/7943189932?check_suite_focus=true#step:4:52), in <module>
    data = {"weather":{"value":wea},"temperature":{"value":temperature},"born_days":{"value":get_count()},"birthday_left":{"value":get_birthday()},"words":{"value":get_words(), "color":get_random_color()}}
  File "/home/runner/work/dailyMessage/dailyMessage/./main.py", line 28, in get_count
    delta = today - datetime.strptime(start_date, "%Y-%m-%d")
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/_strptime.py", line [56](https://github.com/fromann/dailyMessage/runs/7943189932?check_suite_focus=true#step:4:57)8, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y-%m-%d'
Error: Process completed with exit code 1.
~~~
### 下面是我更改完的代码
>> love_days=>born_days 微信模板已同步更改
>> birthday改用切片【5：】
~~~
from datetime import date, datetime
import math
from wechatpy import WeChatClient
from wechatpy.client.api import WeChatMessage, WeChatTemplate
import requests
import os
import random

today = datetime.now()
start_date = os.environ['START_DATE']
city = os.environ['CITY']
birthday = start_date[5:]
app_id = os.environ["APP_ID"]
app_secret = os.environ["APP_SECRET"]
user_id = os.environ["USER_ID"]
template_id = os.environ["TEMPLATE_ID"]

def get_weather():
  url = "http://autodev.openspeech.cn/csp/api/v2.1/weather?openId=aiuicus&clientType=android&sign=android&city=" + city
  res = requests.get(url).json()
  weather = res['data']['list'][0]
  return weather['weather'], math.floor(weather['temp'])

def get_count():
  delta = today - datetime.strptime(start_date, "%Y-%m-%d")
  return delta.days

def get_birthday():
  next = datetime.strptime(str(date.today().year) + "-" + birthday, "%Y-%m-%d")
  if next < datetime.now():
    year=next.year + 1
    next = next.replace(year)
  return (next - today).days

def get_words():
  words = requests.get("https://api.shadiao.pro/chp")
  if words.status_code != 200:
    return get_words()
  return words.json()['data']['text']

def get_random_color():
  return "#%06x" % random.randint(0, 0xFFFFFF)

client = WeChatClient(app_id, app_secret)

wm = WeChatMessage(client)
wea, temperature = get_weather()
data = {"weather":{"value":wea},"temperature":{"value":temperature},"born_days":{"value":get_count()},"birthday_left":{"value":get_birthday()},"words":{"value":get_words(), "color":get_random_color()}}
res = wm.send_template(user_id, template_id, data)
print(res)
~~~

**Comment by fromann** [comment]
Start_date x携程start_data了
