### ISSUE TITLE
这怎么解呀

### ISSUE THREAD

**Issue by ZhangHu77** [rxrw/daily_morning#25]
Traceback (most recent call last):
  File "/home/runner/work/wx_push/wx_push/./main.py", line 51, in <module>
    data = {"weather":{"value":wea},"temperature":{"value":temperature},"love_days":{"value":get_count()},"birthday_left":{"value":get_birthday()},"words":{"value":get_words(), "color":get_random_color()}}
  File "/home/runner/work/wx_push/wx_push/./main.py", line 28, in get_count
    delta = today - datetime.strptime(start_date, "%Y-%m-%d")
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/_strptime.py", line [56](https://github.com/ZhangHu77/wx_push/runs/7948716946?check_suite_focus=true#step:4:57)8, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y-%m-%d'
Error: Process completed with exit code 1.

**Comment by caolizhi** [comment]
START_DATE 格式： 2022-08-23

**Comment by ZhangHu77** [comment]
是我的ssh的原因
