### ISSUE TITLE
Process completed with exit code 1.

### ISSUE THREAD

**Issue by lxamq** [rxrw/daily_morning#38]
提问前翻看一下有没有历史有人提过的问题！
Traceback (most recent call last):
  File "/home/runner/work/-/-/./main.py", line 50, in <module>
    wea, temperature, highest, lowest = get_weather()
  File "/home/runner/work/-/-/./main.py", line 24, in get_weather
    weather = res['data']['list'][0]
IndexError: list index out of range
Error: Process completed with exit code 1.
**描述一下存在的问题**
请在此清楚明白地说明出现的问题，不要给我说 Exit code 1，把最后几行都复制粘贴过来。

**如何产生的**
你的变量如何设置，尤其是城市、两个日期的值和模板是什么样子的

**截图**
将你微信公众平台测试号的模板内容和 Github 的报错截图粘贴过来
![This is an image](
![DZE7UP1X18XC KRASG@256H](https://user-images.githubusercontent.com/110094852/186065091-d783fbf8-8a52-4730-9c01-2370c7d95f9a.png)
)
**其他说明**
写在这里

**Comment by rxrw** [comment]
<img width="622" alt="image" src="https://user-images.githubusercontent.com/9566402/186065191-08ba03c3-d59a-4ae0-b82e-b1be14c92f67.png">

**Comment by lxamq** [comment]
File "/home/runner/work/-/-/./main.py", line 28, in get_count
    delta = today - datetime.strptime(start_date, "%Y-%m-%d")
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/_strptime.py", line [56](https://github.com/lxamq/-/runs/7965824767?check_suite_focus=true#step:4:57)8, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y-%m-%d'
Error: Process completed with exit code 1.

**Comment by lxamq** [comment]
时间格式不匹配？

**Comment by luguodataiyang** [comment]
File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/wechatpy/client/__init__.py", line 60, in fetch_access_token
    return self._fetch_access_token(
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/wechatpy/client/base.py", line 213, in _fetch_access_token
    raise WeChatClientException(
wechatpy.exceptions.WeChatClientException: Error code: 41004, message: appsecret missing rid: 63064a75-4b20b587-16b16360
Error: Process completed with exit code 1.

大佬们帮忙看下这是什么原因
