### ISSUE TITLE
一个一个对着敲的，还是有问题能帮忙看一下吗

### ISSUE THREAD

**Issue by Afwqie** [rxrw/daily_morning#55]
提问前翻看一下有没有历史有人提过的问题！

**描述一下存在的问题**
Collecting xmltodict==0.13.0
  Downloading xmltodict-0.13.0-py2.py3-none-any.whl (10.0 kB)
Installing collected packages: optionaldict, xmltodict, urllib3, six, pycparser, idna, charset-normalizer, certifi, requests, python-dateutil, cffi, wechatpy, cryptography
Successfully installed certifi-2022.6.15 cffi-1.15.1 charset-normalizer-2.1.0 cryptography-37.0.4 idna-3.3 optionaldict-0.1.2 pycparser-2.21 python-dateutil-2.8.2 requests-2.28.1 six-1.16.0 urllib3-1.26.11 wechatpy-1.8.18 xmltodict-0.13.0
Traceback (most recent call last):
  File "/home/runner/work/daily_morning/daily_morning/./main.py", line 54, in <module>
    res = wm.send_template(user_id, template_id, data)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/wechatpy/client/api/message.py", line [60](https://github.com/Afwqie/daily_morning/runs/7989105943?check_suite_focus=true#step:4:61)9, in send_template
    return self._post(
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/wechatpy/client/api/base.py", line 19, in _post
    return self._client.post(url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/wechatpy/client/base.py", line 182, in post
    return self._request(
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/wechatpy/client/base.py", line 77, in _request
    kwargs['params']['access_token'] = self.access_token
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/wechatpy/client/base.py", line 248, in access_token
    self.fetch_access_token()
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/wechatpy/client/__init__.py", line 60, in fetch_access_token
    return self._fetch_access_token(
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/wechatpy/client/base.py", line 213, in _fetch_access_token
    raise WeChatClientException(
wechatpy.exceptions.WeChatClientException: Error code: 40125, message: invalid appsecret rid: [63](https://github.com/Afwqie/daily_morning/runs/7989105943?check_suite_focus=true#step:4:64)05cc41-0be5c5a8-4050bd3e
Error: Process completed with exit code 1.
##[debug]Finishing: Run pip install -r ./requirements.txt && python ./main.py

**如何产生的**
你的变量如何设置，尤其是城市、两个日期的值和模板是什么样子的
均复制粘贴，城市写的是惠州，两个日期按照教程走的

**截图**

**其他说明**
写在这里

**Comment by luguodataiyang** [comment]
我的也是这样报错，你的解决了吗

**Comment by rxrw** [comment]
App secret 刷新一下再填
